﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using FreeAgent.Model;
using Refit;
using System.Text;
using System.Threading.Tasks;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
    }
}

namespace FreeAgent
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIFreeAgentApi : IFreeAgentApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIFreeAgentApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<AccessResponse> RefreshAccessToken(AccessRequest request)
        {
            var arguments = new object[] { request };
            return (Task<AccessResponse>) methodImpls["RefreshAccessToken"](Client, arguments);
        }

        public virtual Task<CompanyWrapper> GetCompanyDetails(string authorization)
        {
            var arguments = new object[] { authorization };
            return (Task<CompanyWrapper>) methodImpls["GetCompanyDetails"](Client, arguments);
        }

        public virtual Task<TaxTimelineWrapper> GetTaxTimelines(string authorization)
        {
            var arguments = new object[] { authorization };
            return (Task<TaxTimelineWrapper>) methodImpls["GetTaxTimelines"](Client, arguments);
        }

        public virtual Task<BankAccountWrapper> BankAccountList(string authorization,string view)
        {
            var arguments = new object[] { authorization,view };
            return (Task<BankAccountWrapper>) methodImpls["BankAccountList"](Client, arguments);
        }

        public virtual Task<BankAccountWrapper> BankAccount(string authorization,int id)
        {
            var arguments = new object[] { authorization,id };
            return (Task<BankAccountWrapper>) methodImpls["BankAccount"](Client, arguments);
        }

        public virtual Task<BankAccountWrapper> CreateBankAccount(string authorization,BankAccountWrapper account)
        {
            var arguments = new object[] { authorization,account };
            return (Task<BankAccountWrapper>) methodImpls["CreateBankAccount"](Client, arguments);
        }

        public virtual Task<BankAccountWrapper> UpdateBankAccount(string authorization,int id,BankAccountWrapper account)
        {
            var arguments = new object[] { authorization,id,account };
            return (Task<BankAccountWrapper>) methodImpls["UpdateBankAccount"](Client, arguments);
        }

        public virtual Task DeleteBankAccount(string authorization,int id)
        {
            var arguments = new object[] { authorization,id };
            return (Task) methodImpls["DeleteBankAccount"](Client, arguments);
        }

        public virtual Task<BillWrapper> GetBillList(string authorization,string view)
        {
            var arguments = new object[] { authorization,view };
            return (Task<BillWrapper>) methodImpls["GetBillList"](Client, arguments);
        }

        public virtual Task<BillWrapper> GetBill(string authorization,int id)
        {
            var arguments = new object[] { authorization,id };
            return (Task<BillWrapper>) methodImpls["GetBill"](Client, arguments);
        }

        public virtual Task<InvoiceWrapper> GetInvoiceList(string authorization,string view,string sort,bool nested_invoice_items)
        {
            var arguments = new object[] { authorization,view,sort,nested_invoice_items };
            return (Task<InvoiceWrapper>) methodImpls["GetInvoiceList"](Client, arguments);
        }

        public virtual Task<InvoiceWrapper> GetInvoice(string authorization,int id)
        {
            var arguments = new object[] { authorization,id };
            return (Task<InvoiceWrapper>) methodImpls["GetInvoice"](Client, arguments);
        }

        public virtual Task<InvoiceWrapper> PostInvoice(string authorization,Invoice invoice)
        {
            var arguments = new object[] { authorization,invoice };
            return (Task<InvoiceWrapper>) methodImpls["PostInvoice"](Client, arguments);
        }

        public virtual System.Threading.Tasks.Task PutInvoiceStatus(string authorization,int id,string transition)
        {
            var arguments = new object[] { authorization,id,transition };
            return (System.Threading.Tasks.Task) methodImpls["PutInvoiceStatus"](Client, arguments);
        }

        public virtual Task<ProjectWrapper> GetProjectList(string authorization,string view)
        {
            var arguments = new object[] { authorization,view };
            return (Task<ProjectWrapper>) methodImpls["GetProjectList"](Client, arguments);
        }

        public virtual Task<InvoiceWrapper> GetProject(string authorization,int id)
        {
            var arguments = new object[] { authorization,id };
            return (Task<InvoiceWrapper>) methodImpls["GetProject"](Client, arguments);
        }

        public virtual Task<ContactWrapper> GetContactList(string authorization,string view,string sort)
        {
            var arguments = new object[] { authorization,view,sort };
            return (Task<ContactWrapper>) methodImpls["GetContactList"](Client, arguments);
        }

        public virtual Task<ContactWrapper> CreateContact(string authorization,ContactWrapper contact)
        {
            var arguments = new object[] { authorization,contact };
            return (Task<ContactWrapper>) methodImpls["CreateContact"](Client, arguments);
        }

        public virtual Task<ContactWrapper> GetContact(string authorization,int id)
        {
            var arguments = new object[] { authorization,id };
            return (Task<ContactWrapper>) methodImpls["GetContact"](Client, arguments);
        }

        public virtual Task DeleteContact(string authorization,int id)
        {
            var arguments = new object[] { authorization,id };
            return (Task) methodImpls["DeleteContact"](Client, arguments);
        }

    }
}


